version: '3.8'

services:
  frontend:
    build:
      context: ./frontend
    ports:
      - "8000:8000"
    volumes:
      - ./frontend:/app
    depends_on:
      - backend
    restart: always
    command: ["npm", "start"]
    environment:
      - CHOKIDAR_USEPOLLING=true
    networks:
      - app-network

  backend:
    build:
      context: ./backend
    ports:
      - "9000:9000"
    volumes:
      - ./backend:/app
    restart: always
    networks:
      - app-network


networks:
  app-network:
    driver: bridge